version: "3.8"

services:
  webauthnappclient:
    build:
      context: .
      dockerfile: Dockerfile
      target: client_build
    image: naveeng9/webauthnapp-client:latest
    ports:
      - "4200:4200" # Angular app accessible at http://localhost:4200
    networks:
      - webauthn-network
    volumes:
      - ./client/src:/app/src # For live development (optional)
    command: ["node_modules/.bin/ng", "serve", "--host", "0.0.0.0"]

  webauthnappnodeserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: naveeng9/webauthnapp-server:latest
    ports:
      - "3000:3000" # Node.js backend accessible at http://localhost:3000
    networks:
      - webauthn-network
    depends_on:
      - webauthnappclient

networks:
  webauthn-network:
    driver: bridge